image: esp8266  #image configured with esp8266 boards TODO: create esp32 board and Rpi0 board

matrix:
  - env: SCRIPT=""

before_install:
  # - if you change the board (generic,wemos...) check board.txt in order to configure correctly all the parameter of arduino --board
  # - cd ~ && cd .. && cd .. && find -name boards.txt
  # - sudo cat /home/abstruse/.arduino15/packages/esp8266/hardware/esp8266/2.5.0/boards.txt
  - arduino --board esp8266:esp8266:nodemcuv2:xtal=80,eesz=4M --save-prefs
  - git clone https://github.com/bblanchon/ArduinoJson.git /home/abstruse/Arduino/libraries/ArduinoJson #Version installed with board manager not working

#include here the library to install
install:
 # - arduino --install-library "ArduinoJson"
  - arduino --install-library "AutoConnect"
  - arduino --install-library "PageBuilder"
  
  

script:
  #- arduino --verify --verbose dooropener.ino #if you have any bug this command will show the verbose compiling
  - arduino --verify dooropener.ino

cache:
