#!/bin/bash --login

DATE=$(date)
echo "File to build $INOFILE"
git config --global user.mail "deploy_bot@yopmail.com"
git config --global user.name "deploy_bot"
	
current_branch=$(echo "$(git branch)"  |  tr -d  \*,[:blank:]) 
echo "branches to deploy: $DEPLOY_BRANCHES"
branches=(${DEPLOY_BRANCHES//;/ })
for branch in "${branches[@]}"
	do 
		 if [ $current_branch = $branch ]
		 then
			git branch -D "$current_branch-BIN" || true && \
			git checkout --orphan "$current_branch-BIN"  && \
			rm -r build || true && \
			git rm --cached -r . -f && \
			mkdir $BUILD_DIRECTORY && \
			bin_path=$(sudo find /tmp -name "$INOFILE.bin") && \
			echo $bin_path && \
			echo $(cat ~/.gitconfig) && \
			cp $bin_path $PWD/$BUILD_DIRECTORY && \
			echo "# Auto generated bin file <br /> Please remove $current_branch-BIN if you don't need anymore <br /> Branch created $DATE" > README.md && \
			git add "README.md" && \
			git add "$BUILD_DIRECTORY" && \
			git commit -m "$DATE Autogenerated bin file" && \
			git push --set-upstream origin  $current_branch-BIN --force && \
			echo "Auto generated bin file successful check $current_branch-BIN branch" 
			exit 0
		else
		echo "$current_branch no added to deploy branch"
		fi
	
	done
exit 0
